Array Indexing and Slicing

In [2]:
import numpy as np

Indexing

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a[3]

np.int64(4)

In [5]:
b = np.array([[0,1,2,3,4],
              [1,2,3,4,5],
              [2,3,4,5,6],
              [7,8,9,10,11]])

In [6]:
b[0,4]

np.int64(4)

In [7]:
b[3,2]

np.int64(9)

Slicing

In [9]:
b[1:4,2:]

array([[ 3,  4,  5],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [10]:
b[:, -2:]

array([[ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [10, 11]])

In [11]:
b[:, 2:]

array([[ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [12]:
b[2:4 ,1:3]

array([[3, 4],
       [8, 9]])

3d array

In [13]:
np.random.seed(99)
arr = np.random.randint(0,10, size =(3,4,3))

In [14]:
arr

array([[[1, 3, 9],
        [8, 9, 8],
        [2, 4, 5],
        [4, 1, 7]],

       [[3, 7, 1],
        [1, 0, 6],
        [4, 7, 2],
        [0, 8, 8]],

       [[4, 9, 7],
        [5, 4, 9],
        [1, 9, 0],
        [5, 9, 3]]], dtype=int32)

In [15]:
arr[1,2,2]

np.int32(2)

nd array slicing

In [17]:
arr[: , : , -1].T

array([[9, 1, 7],
       [8, 6, 9],
       [5, 2, 0],
       [7, 8, 3]], dtype=int32)