In [10]:
import numpy as np

In [11]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [12]:
array = array * 2
array

array([ 2,  4,  6,  8, 10])

In [13]:
array.ndim

1

In [14]:
arry1 = np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]])
arry1.shape

(3, 5)

In [15]:
arry1.ndim

2

In [18]:
np.zeros(shape = (2,3,4), dtype = int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [19]:
np.full(shape = (3,4), fill_value = 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [21]:
np.arange(1,90,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89])

In [27]:
np.linspace((1,50), (30,100), num = 5)

array([[  1.  ,  50.  ],
       [  8.25,  62.5 ],
       [ 15.5 ,  75.  ],
       [ 22.75,  87.5 ],
       [ 30.  , 100.  ]])

In [37]:
np.eye(5,5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.randint(0, 50, size= (2,5))

array([[32,  6, 36,  5, 38],
       [21, 43, 33,  2, 29]], dtype=int32)