Working with Numpy

In [21]:
import numpy as np

np.__version__

'2.4.6'

Creating Numpy array

In [22]:
array1 = np.array([1,2,3,4,5])
array2 = np.random.randint(1,9, size =(3,3))
array3 = np.linspace(0,5,10)

In [23]:
array1

array([1, 2, 3, 4, 5])

In [24]:
array2

array([[7, 1, 6],
       [2, 6, 5],
       [8, 2, 5]], dtype=int32)

In [25]:
array3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Indexing and slicing arrays

In [26]:
array2[1,2]

np.int32(5)

In [27]:
array2[:2,:2]

array([[7, 1],
       [2, 6]], dtype=int32)

In [28]:
array2[2,0] = 100
array2[2,0]

np.int32(100)

Properties and Methods of NumPy Arrays

In [30]:
x = np.random.randint(0,9, size = (3,3))

In [32]:
x.shape

(3, 3)

In [33]:
x.size

9

In [54]:
y = np.array([1,2,3,4,5])
y.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [55]:
y.flatten()

array([1, 2, 3, 4, 5])

Operations on NumPy Arrays

In [56]:
y += 5
y

array([ 6,  7,  8,  9, 10])

In [57]:
y.reshape(5,1)*3

array([[18],
       [21],
       [24],
       [27],
       [30]])

In [64]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.linalg.multi_dot([A,B])

array([[19, 22],
       [43, 50]])

In [70]:
Matrix = np.random.randint(0,9, size =(3,3))
array = np.array([1,2,3])

In [71]:
Matrix

array([[0, 3, 3],
       [5, 2, 0],
       [5, 3, 2]], dtype=int32)

In [72]:
Matrix += array
Matrix

array([[1, 5, 6],
       [6, 4, 3],
       [6, 5, 5]], dtype=int32)