In [6]:
import numpy as np

In [7]:
a = np.random.randint(10,50, size = (2,3,3), dtype= "int16")
a

array([[[42, 48, 22],
        [36, 42, 41],
        [25, 24, 36]],

       [[27, 44, 40],
        [49, 19, 34],
        [45, 45, 12]]], dtype=int16)

In [8]:
a = np.random.randint(10,50, size = (6,4), dtype= "int16")
b = a.reshape(8,3)
a.reshape(2,12)

array([[22, 39, 15, 32, 13, 20, 12, 34, 19, 19, 32, 35],
       [12, 14, 23, 46, 40, 39, 28, 49, 14, 31, 45, 26]], dtype=int16)

In [9]:
b

array([[22, 39, 15],
       [32, 13, 20],
       [12, 34, 19],
       [19, 32, 35],
       [12, 14, 23],
       [46, 40, 39],
       [28, 49, 14],
       [31, 45, 26]], dtype=int16)

In [13]:
a = np.random.randint(10,50, size = (6,4))


In [14]:
a.cumprod(axis = 1)

array([[     33,     660,   30360,  333960],
       [     38,     646,   16796,  470288],
       [     47,    1833,   36660,  586560],
       [     15,     465,    6045,  223665],
       [     33,    1419,   52503, 1890108],
       [     11,     352,    4224,  101376]])

In [15]:
a.cumprod(axis = 0)

array([[       33,        20,        46,        11],
       [     1254,       340,      1196,       308],
       [    58938,     13260,     23920,      4928],
       [   884070,    411060,    310960,    182336],
       [ 29174310,  17675580,  11505520,   6564096],
       [320917410, 565618560, 138066240, 157538304]])

In [23]:
arr1 = np.random.randint(1,50, size = (3,3))
arr2 = np.random.randint(1,50, size = (3,3))


In [24]:
np.concatenate([arr1,arr2])

array([[32, 37, 45],
       [16,  5, 22],
       [26, 42, 17],
       [ 6,  4, 30],
       [38, 35,  5],
       [12, 14, 46]], dtype=int32)

In [22]:
np.concatenate([arr1,arr2],axis= 1)

array([[28,  3,  3,  8,  7, 40],
       [ 5,  4, 31, 25, 33, 45],
       [29, 18, 31, 40, 31, 13]], dtype=int32)