In [25]:
import numpy as np

Numpy Operations

In [26]:
a = np.array(
    [
    [4,6,5,7],
    [1,2,3,4]
    ]
)

b = np.random.randint(1, 45, size= (2,4))
c = np.linspace((0,5),(60,100), num = 7, dtype= int)

a,b,c

(array([[4, 6, 5, 7],
        [1, 2, 3, 4]]),
 array([[23, 20, 40, 40],
        [ 3,  7, 14,  2]], dtype=int32),
 array([[  0,   5],
        [ 10,  20],
        [ 20,  36],
        [ 30,  52],
        [ 40,  68],
        [ 50,  84],
        [ 60, 100]]))

In [27]:
np.add(a,b)

array([[27, 26, 45, 47],
       [ 4,  9, 17,  6]])

In [28]:
np.subtract(a,b)

array([[-19, -14, -35, -33],
       [ -2,  -5, -11,   2]])

In [29]:
np.pow(a,2)

array([[16, 36, 25, 49],
       [ 1,  4,  9, 16]])

In [30]:
np.add(a**2,a**3)

array([[ 80, 252, 150, 392],
       [  2,  12,  36,  80]])

In [31]:
quo, rem = np.divmod(b,a)
rem

array([[3, 2, 0, 5],
       [0, 1, 2, 2]])

TRIGNOMETRIC OPERATIONS

In [32]:
x = np.array([0,30,45,60,90])

np.sin(x)
np.cos(x)
np.tan(x)

cosec = np.reciprocal(np.sin(x))
cosec


C:\Users\bobs9\AppData\Local\Temp\ipykernel_24592\1494176417.py:7: RuntimeWarning: divide by zero encountered in reciprocal
  cosec = np.reciprocal(np.sin(x))


array([        inf, -1.01211335,  1.17522136, -3.28072557,  1.11857241])

In [33]:
sec = np.reciprocal(np.cos(x))
sec

array([ 1.        ,  6.48292123,  1.90359441, -1.04996469, -2.23177613])

In [34]:
cot = np.reciprocal(np.tan(x))
cot

C:\Users\bobs9\AppData\Local\Temp\ipykernel_24592\3399165736.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  cot = np.reciprocal(np.tan(x))


array([        inf, -0.15611995,  0.61736962,  3.12460562, -0.50120278])

Matrix Operation

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])

In [38]:
# transpose
bT = np.transpose(b)

In [ ]:
a @ bT
# np.dot(a, bT)

array([[ 74,  92],
       [182, 227]])

In [40]:
# Trace
d_sum = np.trace(b)
print(d_sum)

26


In [41]:
# Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [ ]:
# Determinant

x= np.random.randint(1,5, size= (4,4))
np.linalg.det(x)

# Inverse

invb = np.linalg.inv(x)
invb

array([[-0.25,  0.25,  0.5 , -0.75],
       [ 0.25, -0.25,  0.5 , -0.25],
       [-1.  ,  0.  ,  0.  ,  1.  ],
       [ 1.5 ,  0.5 , -2.  ,  0.5 ]])

In [50]:
a = np.array([[4,2],[5,3]])
b = np.array([[8],[9]])

a_inv = np.linalg.inv(a)
np.dot(a_inv, b)

array([[ 3.],
       [-2.]])

In [52]:
solution = np.linalg.solve(a,b)
solution

array([[ 3.],
       [-2.]])

In [53]:
solution.T

array([[ 3., -2.]])